clear all
clc
load('fitdata.mat');
[S1, S2] = significance(fitoutput,fitoutputPQSC,fitoutputHAMTL,fitoutputQOD,...
fitoutputSIQE,fitoutputBQMSsiqad,fitoutputSQMS,fitoutputGFM,fitoutputSFUW,fitoutputSVQI,...
fitoutputESIMsiqad,fitoutputSIQM,fitoutputscid,fitoutputPQSCscid,fitoutputHAMTLscid,...
fitoutputQODscid,fitoutputSIQEscid,fitoutputBQMSscid,fitoutputSQMSscid,fitoutputGFMscid,...
fitoutputSFUWscid,fitoutputSVQIscid,fitoutputESIMscid,fitoutputSIQMscid)
